export type HomepageContent = typeof DEFAULT_HOMEPAGE_CONTENT & Record<string, unknown>;

export const DEFAULT_HOMEPAGE_CONTENT = {
  heroGreeting: "Good morning",
  heroWelcome: "Welcome — this is a space for you.",
  heroQuoteEnabled: true,
  heroAcceptingText: "Now Accepting New Clients",
  heroPhoneBadge: "100% Phone-Based",
  heroPrimaryButton: "Begin Your First Session",
  heroSecondaryText: "Support that meets you where you are.",
  heroCardTitle: "Phone consultation",
  heroCardSubtitle: "A calm place to begin",
  heroCardDescription: "Support that meets you where you are.",
  aboutEyebrow: "A grounded space for your next chapter",
  aboutTitle: "Healing begins with being heard.",
  aboutParagraph1: "Aydens Wellness Services offers a warm, judgment-free space to slow down, reflect, and feel supported.",
  aboutParagraph2: "With phone-based consultations, you can connect from the place that already feels safe — no commute, no waiting room, and no pressure to have everything figured out before you begin.",
  aboutParagraph3: "Whether you’re navigating a life transition, managing anxiety, or looking for a grounded presence to talk through the week, you deserve support that honors your pace. Reset, rebuild, and thrive on your own terms.",
  aboutQuote: "Your story deserves space.",
  bookingEyebrow: "Let’s connect",
  bookingTitle: "Make room for your wellbeing.",
  bookingDescription: "Request a brief phone consultation to see if we’re a good fit.",
  bookingInfoTitle: "A gentle place to start",
  bookingPhoneLabel: "Phone consultations",
  bookingPhone: "+1 (561) 291-8556",
  bookingOfficeBadge: "No Physical Office",
  bookingEmailLabel: "Email",
  bookingEmail: "aydenstherapyservices@gmail.com",
  bookingHoursTitle: "Main Office Hours:",
  bookingTherapistHoursTitle: "Therapist Hours:",
  bookingHolidaysTitle: "Upcoming Holidays",
  bookingFormTitle: "Request a consultation",
  bookingManageLink: "Already booked? Manage with your code →",
  bookingNameLabel: "Full Name",
  bookingNamePlaceholder: "Jane Doe",
  bookingPhoneFieldLabel: "Phone Number",
  bookingPhonePlaceholder: "(555) 123-4567",
  bookingReasonLabel: "What would you like support with?",
  bookingReasonPlaceholder: "Share a little about what brings you here...",
  bookingDateLabel: "Preferred Date",
  bookingTimeLabel: "Preferred Time",
  bookingDisclaimer: "This first step is simply a request. All consultations are held by phone.",
  bookingSubmitText: "Request consultation",
  bookingSendingText: "Sending",
  bookingSuccessTitle: "Request Sent!",
  bookingSuccessDescription: "Your booking request has been received. I'll contact you shortly to confirm your session.",
  bookingCodeLabel: "Your Confirmation Code",
  bookingCodeDescription: "Save this code — you can use it to reschedule or cancel your appointment.",
  bookingAnotherButton: "Book Another Session",
  bookingClosedTitle: "Currently Fully Booked",
  bookingClosedDescription: "We are not accepting new session requests at this moment. Please check back later.",
  bookingDateHelp: "Choose a date to see available business hours. Sessions are 60 minutes and must fit within the practice hours.",
  navPrivateSupport: "Private, phone-based support",
  navRegion: "South Florida and beyond",
  navAbout: "Our approach",
  navBook: "How to begin",
  navWellness: "Wellness Journey",
  navStaff: "Staff",
  navClientPortal: "Client portal",
  navRequestCall: "Request a call",
  footerContactHeading: "Contact",
  footerPracticeHeading: "Our practice",
  footerPracticeDescription: "We provide strictly over-the-phone consultations. There is no physical office, allowing you to access support from the comfort of your own space.",
  footerCopyrightText: "Phone consultations only · no physical office",
  logoAlt: "Aydens Wellness Services botanical logo",
  heroImageUrl: "",
  aboutImageUrl: "",
  faviconUrl: "",
  contactPhone: "+1 (561) 291-8556",
  contactEmail: "aydenstherapyservices@gmail.com",
  announcementHeading: "What’s new",
  announcementSubheading: "Updates from Aydens Wellness Services",
  announcementDescription: "",
  announcementImageUrl: "",
} as const;

export function getHomepageContent(settings: unknown) {
  const value = (settings as { homepageContent?: Record<string, unknown> } | undefined)?.homepageContent;
  return { ...DEFAULT_HOMEPAGE_CONTENT, ...(value ?? {}) } as HomepageContent;
}
