import { useState } from 'react';
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Clock3, FileText, LifeBuoy, LogOut, MessageCircle, Plus, UserRound } from 'lucide-react';
import './_group.css';

function Brand() { return <div className="ayden-brand"><span className="ayden-mark">A</span><span>Ayden’s Therapy Services</span></div>; }

export default function ClientPortal() {
  const [tab, setTab] = useState<'home' | 'appointments' | 'support' | 'details'>('home');
  const [requested, setRequested] = useState(false);
  const [message, setMessage] = useState('');
  const [toast, setToast] = useState('');
  const tabs = [{ id: 'home', label: 'Overview' }, { id: 'appointments', label: 'Appointments' }, { id: 'support', label: 'Support' }, { id: 'details', label: 'My details' }] as const;
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2200); };

  return <div className="ayden-root ayden-client ayden-noise">
    <header className="ayden-client-header"><div className="ayden-shell"><Brand /><div style={{ display: 'flex', alignItems: 'center', gap: 18 }}><span className="ayden-mono" style={{ color: 'var(--ay-ink-soft)' }}>Private client space</span><button className="ayden-btn small ghost" onClick={() => notify('You are signed out of the demo')}><LogOut size={13} /> Sign out</button></div></div></header>
    <main className="ayden-shell ayden-client-main">
      <div className="ayden-client-intro">
        <div><div className="ayden-mono ayden-kicker">Tuesday, June 18, 2024</div><h1 className="ayden-display ayden-client-title">Welcome back, Morgan.</h1><p style={{ margin: 0, color: 'var(--ay-ink-soft)', fontSize: 13 }}>A calm place to keep the practical pieces of care together.</p></div>
        <div className="ayden-pill" style={{ background: 'var(--ay-sun)', borderColor: 'var(--ay-sun)' }}><span style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--ay-sea-deep)' }} /> Account in good standing</div>
      </div>
      <nav className="ayden-client-nav">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
      {tab === 'home' && <div className="ayden-fade">
        <div className="ayden-client-grid">
          <section className="ayden-next"><div className="ayden-mono">Next phone session</div><div className="ayden-next-date"><span className="ayden-next-day ayden-display">24</span><span className="ayden-next-meta">June<br /><strong style={{ color: 'var(--ay-paper)' }}>Monday</strong></span></div><div className="ayden-next-foot"><span><Clock3 size={13} style={{ verticalAlign: 'middle', marginRight: 5 }} />10:00 am – 11:00 am</span><span>with Dr. Ayden</span></div></section>
          <section className="ayden-personal-card"><div className="ayden-mono" style={{ color: 'var(--ay-coral)' }}>A note for today</div><div className="ayden-display">You can take the next step slowly.</div><p>There is no prize for rushing the work. Bring what is present, and we can begin there.</p></section>
        </div>
        <div className="ayden-client-lower">
          <section className="ayden-card ayden-list"><div className="ayden-panel-head" style={{ padding: '0 0 12px' }}><div><div className="ayden-mono ayden-kicker">Stay connected</div><div className="ayden-panel-title" style={{ marginTop: 7 }}>Your care, in view</div></div><ArrowUpRight size={15} color="var(--ay-coral)" /></div><div className="ayden-list-item"><div className="ayden-list-icon"><CalendarDays size={15} /></div><div><strong>One upcoming appointment</strong><p>Your next session is confirmed for June 24 at 10:00 am.</p></div></div><div className="ayden-list-item"><div className="ayden-list-icon"><MessageCircle size={15} /></div><div><strong>Need to reach the team?</strong><p>Send a private message about scheduling or your account.</p><button className="ayden-link" onClick={() => setTab('support')} style={{ border: 0, background: 'transparent', padding: 0, marginTop: 7, fontWeight: 800, fontSize: 10 }}>Open support →</button></div></div></section>
          <section className="ayden-card ayden-list"><div className="ayden-panel-head" style={{ padding: '0 0 12px' }}><div><div className="ayden-mono ayden-kicker">Helpful to have nearby</div><div className="ayden-panel-title" style={{ marginTop: 7 }}>Your care notes</div></div><FileText size={15} color="var(--ay-coral)" /></div><div className="ayden-list-item"><div className="ayden-list-icon" style={{ background: 'var(--ay-sea)' }}>01</div><div><strong>Before your next session</strong><p>Notice one moment this week when your body felt at ease, even briefly.</p></div></div><div className="ayden-list-item"><div className="ayden-list-icon" style={{ background: 'var(--ay-sea)' }}>02</div><div><strong>Phone session reminder</strong><p>We’ll call the number ending in 8556. Find a private place where you can settle in.</p></div></div></section>
        </div>
      </div>}
      {tab === 'appointments' && <section className="ayden-card ayden-fade" style={{ padding: 22 }}><div className="ayden-panel-head" style={{ padding: '0 0 17px' }}><div><div className="ayden-mono ayden-kicker">Your calendar</div><div className="ayden-panel-title" style={{ marginTop: 7 }}>Appointments</div></div><button className="ayden-btn small sun" onClick={() => setRequested(true)}><Plus size={14} /> Request a session</button></div>{requested ? <div style={{ padding: '23px 0', borderBottom: '1px solid var(--ay-line)' }}><div className="ayden-display" style={{ fontSize: 33 }}>What would you like to schedule?</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginTop: 18, maxWidth: 500 }}><input className="ayden-input" type="date" /><input className="ayden-input" type="time" /></div><div style={{ display: 'flex', gap: 9, marginTop: 14 }}><button className="ayden-btn small" onClick={() => { setRequested(false); notify('Session request sent to the care team'); }}>Send request <ArrowUpRight size={13} /></button><button className="ayden-btn small ghost" onClick={() => setRequested(false)}>Cancel</button></div></div> : null}<div style={{ padding: '20px 0', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--ay-line)' }}><div style={{ display: 'flex', gap: 14, alignItems: 'center' }}><div className="ayden-list-icon"><CalendarDays size={16} /></div><div><strong style={{ fontSize: 13 }}>Monday, June 24</strong><p style={{ margin: '5px 0 0', color: 'var(--ay-ink-soft)', fontSize: 11 }}>10:00 am · Phone session with Dr. Ayden</p></div></div><span className="ayden-status">Confirmed</span></div><div style={{ paddingTop: 20, color: 'var(--ay-ink-soft)', fontSize: 11 }}>Your confirmation code <strong style={{ color: 'var(--ay-ink)', fontFamily: 'Space Mono' }}>ATS-4821</strong></div></section>}
      {tab === 'support' && <section className="ayden-client-grid ayden-fade"><div className="ayden-card" style={{ padding: 22 }}><div className="ayden-mono ayden-kicker">Private message</div><div className="ayden-display" style={{ fontSize: 38, lineHeight: .95, marginTop: 14 }}>How can we help?</div><p style={{ color: 'var(--ay-ink-soft)', fontSize: 11, lineHeight: 1.6 }}>For scheduling, account questions, or anything you’d like the care team to know.</p><textarea className="ayden-input ayden-textarea" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write your message here." /><button className="ayden-btn" style={{ marginTop: 14 }} onClick={() => { setMessage(''); notify('Message sent privately to the care team'); }}>Send message <ArrowUpRight size={14} /></button></div><div className="ayden-card" style={{ padding: 22, background: 'var(--ay-sea)' }}><LifeBuoy size={19} /><div className="ayden-display" style={{ fontSize: 32, marginTop: 22 }}>You’re not interrupting.</div><p style={{ color: 'var(--ay-ink-soft)', fontSize: 12, lineHeight: 1.7 }}>The support inbox is checked during practice hours. For urgent help, please contact local emergency services.</p><div className="ayden-rule" style={{ marginTop: 24, paddingTop: 14, fontSize: 11 }}>Practice hours<br /><strong>Mon–Thu 9:00 am–6:00 pm</strong></div></div></section>}
      {tab === 'details' && <section className="ayden-card ayden-fade" style={{ padding: 22, maxWidth: 630 }}><div className="ayden-mono ayden-kicker">Your information</div><div className="ayden-display" style={{ fontSize: 38, marginTop: 12 }}>My details</div><p style={{ color: 'var(--ay-ink-soft)', fontSize: 11 }}>Keep your contact information current so the team can reach you.</p><div style={{ display: 'grid', gap: 16, marginTop: 24 }}><label className="ayden-field"><span className="ayden-label">Full name</span><input className="ayden-input" defaultValue="Morgan Lee" /></label><label className="ayden-field"><span className="ayden-label">Email</span><input className="ayden-input" defaultValue="morgan.lee@example.com" /></label><label className="ayden-field"><span className="ayden-label">Phone</span><input className="ayden-input" defaultValue="(561) 291-8556" /></label></div><button className="ayden-btn" style={{ marginTop: 20 }} onClick={() => notify('Your details have been saved')}><Check size={14} /> Save details</button></section>}
    </main>
    {toast && <div className="ayden-toast">{toast}</div>}
  </div>;
}