import { useEffect, useState } from "react";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Wand2, Send, Eye, RefreshCw, CheckCircle2 } from "lucide-react";

export default function AssignmentStudio(){
 const {toast}=useToast();const [prompt,setPrompt]=useState(""),[draft,setDraft]=useState<any>(null),[previewToken,setPreviewToken]=useState(""),[clients,setClients]=useState<any[]>([]),[query,setQuery]=useState(""),[client,setClient]=useState<any>(null),[dueDate,setDueDate]=useState(""),[busy,setBusy]=useState(false),[assignments,setAssignments]=useState<any[]>([]);
 const load=async()=>{try{const [a,c]=await Promise.all([customFetch<any[]>("/api/advanced/staff/assignments",{responseType:"json"}),query.length>=2?customFetch<any>("/api/clients/search?q="+encodeURIComponent(query),{responseType:"json"}):Promise.resolve({clients:[]})]);setAssignments(a);setClients(c.clients||[]);}catch(e:any){toast({variant:"destructive",title:"Assignment Studio failed",description:e?.message||"Refresh and try again."});}};
 useEffect(()=>{void load();},[query]);
 const generate=async()=>{if(!prompt.trim())return;setBusy(true);try{const d=await customFetch<any>("/api/advanced/staff/assignment-preview",{method:"POST",body:JSON.stringify({prompt}),responseType:"json"});setDraft(d);setPreviewToken(d.previewToken);toast({title:"Draft ready for review"});}catch(e:any){toast({variant:"destructive",title:"AI draft failed",description:e?.message||"Check OPENAI_API_KEY and OPENAI_MODEL."});}finally{setBusy(false);}};
 const send=async()=>{if(!draft||!previewToken||!client){toast({variant:"destructive",title:"Choose a client"});return;}setBusy(true);try{await customFetch("/api/advanced/staff/assignments/send",{method:"POST",body:JSON.stringify({previewToken,clientId:client.clientAccountId,title:draft.title,summary:draft.summary,instructions:draft.instructions,type:draft.type,frequency:draft.frequency,dueDate:dueDate||null,config:draft.config}),responseType:"json"});toast({title:"Assignment sent",description:"It is now available in the client's Wellness Center."});setDraft(null);setPreviewToken("");setPrompt("");setClient(null);setDueDate("");await load();}catch(e:any){toast({variant:"destructive",title:"Assignment was not sent",description:e?.message||"You must preview the assignment before sending."});}finally{setBusy(false);}};
 const summarize=async()=>{if(!draft?.instructions)return;try{const r=await customFetch<any>("/api/advanced/staff/assignment-summarize",{method:"POST",body:JSON.stringify({content:draft.instructions}),responseType:"json"});setDraft({...draft,summary:r.summary});}catch(e:any){toast({variant:"destructive",title:"Summary failed",description:e?.message||"Try again."});}};
 return <div className="space-y-7"><div><p className="text-sm text-muted-foreground">Create interactive client assignments with an AI draft, mandatory review, and live progress.</p><h1 className="text-3xl font-serif font-bold">Assignment Studio</h1></div>
 <div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2"><Wand2 className="h-5 w-5 text-primary"/>Create with Aubrey's AI</CardTitle><CardDescription>Describe what you want. Nothing is sent until you preview it and explicitly approve it.</CardDescription></CardHeader><CardContent className="space-y-4"><Textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={7} placeholder="Example: Make a 4-week weekly assignment where the client tracks three things that helped them feel calmer each week."/><Button onClick={()=>void generate()} disabled={busy||!prompt.trim()}><Wand2 className="mr-2 h-4 w-4"/>{busy?"Generating…":"Generate draft"}</Button>{draft&&<div className="space-y-4 rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-center justify-between gap-3"><Badge>Preview only</Badge><Eye className="h-5 w-5 text-primary"/></div><Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><Textarea value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})} rows={10}/><Textarea value={draft.summary||""} onChange={e=>setDraft({...draft,summary:e.target.value})} rows={3} placeholder="Short summary shown to the client"/><div className="grid gap-3 sm:grid-cols-2"><div><label className="text-xs font-semibold text-muted-foreground">Type</label><p className="mt-1 rounded-xl bg-background p-3 text-sm capitalize">{draft.type}</p></div><div><label className="text-xs font-semibold text-muted-foreground">Frequency</label><Input value={draft.frequency||"one_time"} onChange={e=>setDraft({...draft,frequency:e.target.value})}/></div></div><Button type="button" variant="outline" onClick={()=>void summarize()} disabled={busy}>AI summarize instructions</Button></div>}</CardContent></Card>
 <Card className="rounded-2xl"><CardHeader><CardTitle>Client & send</CardTitle><CardDescription>Choose the client after reviewing the draft. The server rejects sends without a preview token.</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search client name, phone, or confirmation code"/>{clients.flatMap((c:any)=>(c.bookings||[]).slice(-1).map((b:any)=><button type="button" key={b.id} className={"w-full rounded-xl border p-3 text-left "+(client?.clientAccountId===c.clientAccountId?"bg-primary/10":"")} onClick={()=>setClient(c)}><p className="font-medium">{c.clientName}</p><p className="text-xs text-muted-foreground">{c.phone} · {b.confirmationCode}</p></button>))}{client&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-4"><p className="font-semibold">{client.clientName}</p><p className="text-xs text-muted-foreground">Portal account linked</p></div>}<Input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} /><Button className="w-full" disabled={!draft||!previewToken||!client||busy} onClick={()=>void send()}><Send className="mr-2 h-4 w-4"/>Send assignment</Button></CardContent></Card></div>
 <Card className="rounded-2xl"><CardHeader><CardTitle>Live assignment progress</CardTitle><CardDescription>See what clients are actually completing, not just what was assigned.</CardDescription></CardHeader><CardContent className="space-y-3">{assignments.map((a:any)=><div key={a.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{a.clientName||"Client"} · {a.title}</p><p className="text-xs text-muted-foreground">{a.type} · {a.status}</p></div><Badge>{a.percent||0}%</Badge></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:(a.percent||0)+"%"}}/></div></div>)}{!assignments.length&&<div className="p-8 text-center text-sm text-muted-foreground">No interactive assignments yet.</div>}</CardContent></Card>
 </div>;
}