import { useState } from "react";
import { customFetch, useGetAuthMe } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, Send, CheckCircle2, ShieldCheck } from "lucide-react";
export default function Aurora(){
 const {data:session}=useGetAuthMe({query:{retry:false}});const {toast}=useToast();
 const [messages,setMessages]=useState<any[]>([]);const [input,setInput]=useState("");const [action,setAction]=useState<any>(null);const [busy,setBusy]=useState(false);
 const ask=async()=>{if(!input.trim())return;const text=input.trim();setBusy(true);try{const result=await customFetch<any>("/api/final/aurora/plan",{method:"POST",body:JSON.stringify({message:text}),responseType:"json"});setMessages(m=>m.concat([{role:"user",body:text},{role:"assistant",body:result.response}]));setAction(result.action||null);setInput("");}catch(e:any){toast({variant:"destructive",title:"Aydens Wellness Staff Assistant unavailable",description:e?.message||"Check the AI configuration or your permissions."});}finally{setBusy(false);}};
 const apply=async()=>{if(!action)return;setBusy(true);try{await customFetch("/api/final/aurora/execute",{method:"POST",body:JSON.stringify({action,request:messages.filter(m=>m.role==="user").at(-1)?.body||""}),responseType:"json"});toast({title:"Aurora completed the action"});setMessages(m=>m.concat([{role:"system",body:"The confirmed action was applied successfully."}]));setAction(null);}catch(e:any){toast({variant:"destructive",title:"Action blocked",description:e?.message||"That action is outside your current staff permissions."});}finally{setBusy(false);}};
 return <div className="max-w-6xl space-y-7"><div><p className="text-sm text-muted-foreground">Private staff AI</p><h1 className="flex items-center gap-2 font-serif text-4xl"><Sparkles className="h-7 w-7 text-primary"/>Aydens Wellness Staff Assistant</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Aurora can review the staff workspace using the data your role is allowed to see and prepare changes for you. Every write is permission-checked again before it runs.</p></div>
 <div className="grid gap-5 lg:grid-cols-[1.1fr,.9fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Ask Aurora</CardTitle><CardDescription>{session?.role||"staff"} access · permission-aware</CardDescription></CardHeader><CardContent className="space-y-4"><div className="min-h-80 space-y-3 rounded-xl bg-muted/20 p-4">{messages.length?messages.map((m,i)=><div key={i} className={"rounded-xl p-3 text-sm "+(m.role==="user"?"ml-8 bg-primary text-primary-foreground":"mr-8 border bg-background")}>{m.body}</div>):<p className="text-sm text-muted-foreground">Try “what needs attention today?” or ask Aurora to prepare a specific change.</p>}</div><Textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask Aydens Wellness Staff Assistant…"/><Button onClick={()=>void ask()} disabled={busy||!input.trim()}><Send className="mr-2 h-4 w-4"/>Ask Aurora</Button></CardContent></Card>
 <Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/>Action preview</CardTitle><CardDescription>Aurora cannot silently change anything.</CardDescription></CardHeader><CardContent>{action?<div className="space-y-4"><Badge>Preview only</Badge><div className="rounded-xl border bg-muted/20 p-4"><p className="font-medium">{String(action.type||"").replaceAll("_"," ")}</p><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(action.args,null,2)}</pre></div><div className="flex flex-wrap gap-2"><Button onClick={()=>void apply()} disabled={busy}><CheckCircle2 className="mr-2 h-4 w-4"/>Confirm & apply</Button><Button variant="outline" onClick={()=>setAction(null)}>Cancel</Button></div></div>:<p className="text-sm leading-6 text-muted-foreground">When Aurora proposes a change, you’ll see the exact action here before it happens.</p>}</CardContent></Card></div>
 </div>;
}