import { useEffect, useState } from "react";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Plus, Save, Trash2, ShieldCheck } from "lucide-react";

export default function Roles(){
 const {toast}=useToast();const [roles,setRoles]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[newName,setNewName]=useState("");
 const load=async()=>{try{const data=await customFetch<any>("/api/advanced/staff/roles",{responseType:"json"});setRoles(data.roles||[]);setPermissions(data.permissions||[]);setSelected((old:any)=>old?data.roles.find((r:any)=>r.id===old.id)||data.roles[0]:data.roles[0]);}catch(e:any){toast({variant:"destructive",title:"Roles could not load",description:e?.message||"Founder access is required."});}};
 useEffect(()=>{void load();},[]);
 const save=async()=>{if(!selected)return;try{await customFetch("/api/advanced/staff/roles/"+selected.id,{method:"PATCH",body:JSON.stringify({name:selected.name,permissions:selected.permissions}),responseType:"json"});await load();toast({title:"Role saved"});}catch(e:any){toast({variant:"destructive",title:"Role save failed",description:e?.message||"Try again."});}};
 const create=async()=>{if(!newName.trim())return;const perms=Object.fromEntries(permissions.map((p:any)=>[p[0],false]));try{await customFetch("/api/advanced/staff/roles",{method:"POST",body:JSON.stringify({name:newName,permissions:perms}),responseType:"json"});setNewName("");await load();toast({title:"Custom role created"});}catch(e:any){toast({variant:"destructive",title:"Could not create role",description:e?.message||"Try again."});}};
 const remove=async()=>{if(!selected||selected.builtIn)return;if(!window.confirm("Delete this custom role?"))return;try{await customFetch("/api/advanced/staff/roles/"+selected.id,{method:"DELETE",responseType:"json"});await load();}catch(e:any){toast({variant:"destructive",title:"Role could not be deleted",description:e?.message||"Move staff out of this role first."});}};
 return <div className="space-y-7"><div><p className="text-sm text-muted-foreground">Founder-only control over staff roles and capabilities.</p><h1 className="text-3xl font-serif font-bold flex items-center gap-2"><ShieldCheck className="h-6 w-6 text-primary"/>Roles & Permissions</h1></div><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Roles</CardTitle><CardDescription>Manager, Therapist, Customer Service Representative, Receptionist, plus your custom roles.</CardDescription></CardHeader><CardContent className="space-y-2">{roles.map((r:any)=><button key={r.id} type="button" className={"w-full rounded-xl border p-3 text-left "+(selected?.id===r.id?"border-primary bg-primary/5":"")} onClick={()=>setSelected(r)}><div className="flex items-center justify-between"><span className="font-medium">{r.name}</span>{r.builtIn?<Badge variant="secondary">Built in</Badge>:<Badge variant="outline">Custom</Badge>}</div></button>)}<div className="mt-4 flex gap-2"><Input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="New role name"/><Button size="icon" onClick={()=>void create()}><Plus className="h-4 w-4"/></Button></div></CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle>{selected?.name||"Choose a role"}</CardTitle><CardDescription>Turn individual capabilities on or off. Founder access remains unrestricted.</CardDescription></CardHeader><CardContent className="space-y-3">{permissions.map((p:any)=><label key={p[0]} className="flex items-center justify-between gap-4 rounded-xl border p-3"><span><span className="block font-medium text-sm">{p[1]}</span><span className="text-xs text-muted-foreground">{p[0]}</span></span><Checkbox checked={selected?.permissions?.[p[0]]===true} onCheckedChange={(v)=>setSelected((old:any)=>({...old,permissions:{...(old?.permissions||{}),[p[0]]:Boolean(v)}}))}/></label>)}<div className="flex flex-wrap gap-2"><Button onClick={()=>void save()} disabled={!selected}><Save className="mr-2 h-4 w-4"/>Save role</Button>{selected&&!selected.builtIn&&<Button variant="outline" className="text-destructive" onClick={()=>void remove()}><Trash2 className="mr-2 h-4 w-4"/>Delete role</Button>}</div></CardContent></Card></div></div>;
}