import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getClientNotificationsQueryKey, getRolloutClientsQueryKey, useRolloutClients, useSendRollout } from '@workspace/api-client-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Send, Users } from 'lucide-react';

export default function Rollout() {
  const { data: clients = [], isLoading } = useRolloutClients();
  const [form, setForm] = useState({ title: '', body: '', audience: 'client' as 'client' | 'opted_in', clientId: '' });
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const send = useSendRollout({ mutation: { onSuccess: (result) => { queryClient.invalidateQueries({ queryKey: getRolloutClientsQueryKey() }); queryClient.invalidateQueries({ queryKey: getClientNotificationsQueryKey() }); setForm({ title: '', body: '', audience: 'client', clientId: '' }); toast({ title: 'Rollout sent', description: `${result.sent} client notification${result.sent === 1 ? '' : 's'} created.` }); }, onError: (error) => toast({ variant: 'destructive', title: 'Rollout failed', description: (error as any)?.data?.error ?? 'Please try again.' }) } });
  const optedInCount = clients.filter((client) => client.updatesOptIn).length;
  return <div className="space-y-7"><div><p className="text-sm text-muted-foreground">Direct client updates</p><h1 className="text-3xl font-semibold">Rollout</h1><p className="mt-2 text-muted-foreground">Push a notification to one client or to every client who opted in for updates.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Message rollout</CardTitle><CardDescription>Notifications appear in the client portal notification wall.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); send.mutate({ title: form.title, body: form.body, audience: form.audience, clientId: form.audience === 'client' ? Number(form.clientId) : undefined }); }}><div className="flex gap-2"><button type="button" onClick={() => setForm({ ...form, audience: 'client' })} className={`rounded-xl border px-4 py-2 text-sm ${form.audience === 'client' ? 'border-primary bg-primary/10 text-primary' : ''}`}>Specific client</button><button type="button" onClick={() => setForm({ ...form, audience: 'opted_in' })} className={`rounded-xl border px-4 py-2 text-sm ${form.audience === 'opted_in' ? 'border-primary bg-primary/10 text-primary' : ''}`}>Opted-in updates</button></div>{form.audience === 'client' && <div className="space-y-2"><Label>Client</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.clientId} onChange={(event) => setForm({ ...form, clientId: event.target.value })} required><option value="">Choose a client…</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name} · {client.email}</option>)}</select></div>}<div className="space-y-2"><Label>Title</Label><Input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /></div><div className="space-y-2"><Label>Message</Label><Textarea className="min-h-36" value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} required /></div><Button disabled={send.isPending || (form.audience === 'client' && !form.clientId)}><Send className="h-4 w-4" /> {send.isPending ? 'Sending…' : 'Send message rollout'}</Button></form></CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" /> Audience</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold">{isLoading ? '—' : optedInCount}</p><p className="text-sm text-muted-foreground">clients opted in for updates</p><div className="mt-5 space-y-2">{clients.slice(0, 8).map((client) => <div key={client.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{client.name}</span><span className={client.updatesOptIn ? 'text-primary' : 'text-muted-foreground'}>{client.updatesOptIn ? 'Opted in' : 'Not opted in'}</span></div>)}</div></CardContent></Card></div></div>;
}