import { useEffect, useState } from "react";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { ClipboardList, Send, CheckCircle2, MessageCircle } from "lucide-react";
export default function StaffRequests(){
 const {toast}=useToast();const [items,setItems]=useState<any[]>([]);const [people,setPeople]=useState<any[]>([]);const [form,setForm]=useState({assigneeEmail:"",title:"",description:"",priority:"normal",dueDate:""});const [comment,setComment]=useState<Record<number,string>>({});
 const load=async()=>{try{const [i,p]=await Promise.all([customFetch<any[]>("/api/final/requests",{responseType:"json"}),customFetch<any[]>("/api/final/requests/people",{responseType:"json"})]);setItems(i||[]);setPeople(p||[]);}catch(e:any){toast({variant:"destructive",title:"Staff Requests unavailable",description:e?.message||"Your role may not have request access."});}};
 useEffect(()=>{void load();},[]);
 const create=async()=>{try{await customFetch("/api/final/requests",{method:"POST",body:JSON.stringify(form),responseType:"json"});setForm({assigneeEmail:"",title:"",description:"",priority:"normal",dueDate:""});toast({title:"Request sent"});await load();}catch(e:any){toast({variant:"destructive",title:"Request failed",description:e?.message||"Try again."});}};
 const update=async(id:number,status:string)=>{try{await customFetch("/api/final/requests/"+id,{method:"PATCH",body:JSON.stringify({status}),responseType:"json"});await load();}catch(e:any){toast({variant:"destructive",title:"Could not update request",description:e?.message||"Try again."});}};
 const addComment=async(id:number)=>{if(!comment[id]?.trim())return;try{await customFetch("/api/final/requests/"+id+"/comments",{method:"POST",body:JSON.stringify({body:comment[id]}),responseType:"json"});setComment(c=>({...c,[id]:""}));await load();}catch(e:any){toast({variant:"destructive",title:"Could not add comment",description:e?.message||"Try again."});}};
 return <div className="max-w-6xl space-y-7"><div><p className="text-sm text-muted-foreground">Team coordination</p><h1 className="flex items-center gap-2 font-serif text-4xl"><ClipboardList className="h-7 w-7 text-primary"/>Staff Requests</h1><p className="mt-2 text-sm text-muted-foreground">Send a request to another employee, track it, and keep comments with the work.</p></div>
 <Card className="rounded-2xl"><CardHeader><CardTitle>New request</CardTitle><CardDescription>Requests are visible to the requester, assignee, and founder.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-5"><Select value={form.assigneeEmail} onValueChange={v=>setForm(f=>({...f,assigneeEmail:v}))}><SelectTrigger><SelectValue placeholder="Assign to…"/></SelectTrigger><SelectContent>{people.map(p=><SelectItem key={p.email} value={p.email}>{p.name} · {p.role}</SelectItem>)}</SelectContent></Select><Input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="What do you need?"/><Textarea className="md:col-span-2" value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} placeholder="Details…"/><div className="space-y-2"><Select value={form.priority} onValueChange={v=>setForm(f=>({...f,priority:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="low">Low</SelectItem><SelectItem value="normal">Normal</SelectItem><SelectItem value="high">High</SelectItem><SelectItem value="urgent">Urgent</SelectItem></SelectContent></Select><Input type="date" value={form.dueDate} onChange={e=>setForm(f=>({...f,dueDate:e.target.value}))}/><Button className="mt-1 w-full" onClick={()=>void create()} disabled={!form.assigneeEmail||!form.title.trim()}><Send className="mr-2 h-4 w-4"/>Send request</Button></div></CardContent></Card>
 <div className="space-y-4">{items.map(item=><Card key={item.id} className="rounded-2xl"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-xl">{item.title}</CardTitle><CardDescription>{item.requesterName||item.requesterEmail} → {item.assigneeName||item.assigneeEmail} · {item.priority}</CardDescription></div><Badge>{item.status.replace("_"," ")}</Badge></div></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap text-sm text-muted-foreground">{item.description}</p>{item.dueDate&&<p className="text-xs text-muted-foreground">Due {item.dueDate}</p>}<div className="space-y-2">{(item.comments||[]).map((c:any)=><div key={c.id} className="rounded-xl bg-muted/30 p-3 text-sm"><p className="text-xs font-semibold text-muted-foreground">{c.authorName} · {new Date(c.createdAt).toLocaleString()}</p><p className="mt-1 whitespace-pre-wrap">{c.body}</p></div>)}</div><div className="flex flex-wrap gap-2">{["open","in_progress","completed","incomplete"].map(s=><Button key={s} variant={item.status===s?"default":"outline"} size="sm" onClick={()=>void update(item.id,s)}>{s==="completed"?<CheckCircle2 className="mr-1 h-4 w-4"/>:null}{s.replace("_"," ")}</Button>)}</div><div className="flex gap-2"><Input value={comment[item.id]||""} onChange={e=>setComment(c=>({...c,[item.id]:e.target.value}))} placeholder="Add a comment…"/><Button variant="outline" onClick={()=>void addComment(item.id)}><MessageCircle className="h-4 w-4"/></Button></div></CardContent></Card>)}</div>
 </div>;
}