// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ayden-redesign/ClientPortal.tsx": () => import("../components/mockups/ayden-redesign/ClientPortal.tsx"),
  "./components/mockups/ayden-redesign/PublicSite.tsx": () => import("../components/mockups/ayden-redesign/PublicSite.tsx"),
  "./components/mockups/ayden-redesign/StaffWorkspace.tsx": () => import("../components/mockups/ayden-redesign/StaffWorkspace.tsx")
};
