import { useEffect, useState } from "react";
import { useRoute, useLocation } from "wouter";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { MessageCircle, Send, ShieldCheck } from "lucide-react";
export default function PublicSupport(){
 const [,setLocation]=useLocation();const [match,params]=useRoute("/support/:token");const token=match?params?.token:null;
 const [name,setName]=useState("");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [subject,setSubject]=useState("Support request");const [message,setMessage]=useState("");const [thread,setThread]=useState<any>(null);const [busy,setBusy]=useState(false);
 const load=async()=>{if(!token)return;try{setThread(await customFetch<any>("/api/final/public-support/"+token,{responseType:"json"}));}catch{}};
 useEffect(()=>{void load();},[token]);
 const start=async()=>{if(name.trim().length<2||!email.includes("@")||!message.trim())return;setBusy(true);try{const result=await customFetch<any>("/api/final/public-support",{method:"POST",body:JSON.stringify({name,email,phone,subject,message}),responseType:"json"});setLocation("/support/"+result.token);}catch(e:any){alert(e?.message||"Could not start support conversation.");}finally{setBusy(false);}};
 const reply=async()=>{if(!token||!message.trim())return;setBusy(true);try{await customFetch("/api/final/public-support/"+token,{method:"POST",body:JSON.stringify({message}),responseType:"json"});setMessage("");await load();}catch(e:any){alert(e?.message||"Could not send message.");}finally{setBusy(false);}};
 return <main className="min-h-screen bg-background px-4 py-12"><div className="mx-auto max-w-3xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Aydens Wellness Services</p><h1 className="mt-2 flex items-center gap-2 font-serif text-5xl"><MessageCircle className="h-7 w-7 text-primary"/>Talk to the team</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Start a support conversation directly from the website. This is for non-emergency coordination and general support, not emergency response.</p></div>
 {thread?<Card className="rounded-2xl"><CardHeader><CardTitle>{thread.subject}</CardTitle><CardDescription>Keep this private link to continue the conversation.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-3">{thread.messages?.map((m:any)=><div key={m.id} className={"rounded-xl p-3 text-sm "+(m.senderType==="staff"?"mr-8 bg-primary/10":"ml-8 bg-muted")}><p className="text-xs font-semibold text-muted-foreground">{m.senderName}</p><p className="mt-1 whitespace-pre-wrap">{m.body}</p></div>)}</div><Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Continue the conversation…"/><Button onClick={()=>void reply()} disabled={busy||!message.trim()}><Send className="mr-2 h-4 w-4"/>Send</Button></CardContent></Card>:<Card className="rounded-2xl"><CardHeader><CardTitle>Start a conversation</CardTitle><CardDescription>We use your contact information to respond to this support request.</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><Input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email"/><Input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number"/><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="How can the team help?"/><div className="rounded-xl border bg-muted/20 p-3 text-xs text-muted-foreground"><ShieldCheck className="mr-1 inline h-4 w-4 text-primary"/>Please do not send emergency details or highly sensitive information here.</div><Button onClick={()=>void start()} disabled={busy||name.trim().length<2||!email.includes("@")||!message.trim()}><Send className="mr-2 h-4 w-4"/>Start support conversation</Button></CardContent></Card>} </div></main>;
}