import { useEffect, useRef, useState } from "react";
import { useRoute, Link } from "wouter";
import { customFetch } from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Upload, CheckCircle2, ShieldCheck, ArrowLeft } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function PublicUpload(){
  const [,params]=useRoute("/upload/:token"); const token=params?.token||"";
  const {toast}=useToast(); const inputRef=useRef<HTMLInputElement>(null);
  const [info,setInfo]=useState<any>(null); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [progress,setProgress]=useState(0);
  useEffect(()=>{if(token)customFetch<any>("/api/advanced/uploads/public/"+token,{responseType:"json"}).then(setInfo).catch(()=>setInfo({error:"This upload link is expired or unavailable."}));},[token]);
  const submit=async()=>{if(!file)return;setBusy(true);setProgress(20);try{const bytes=new Uint8Array(await file.arrayBuffer());let binary="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));const encoded=btoa(binary);setProgress(60);await customFetch("/api/advanced/uploads/public/"+token,{method:"POST",body:JSON.stringify({fileName:file.name,mimeType:file.type,data:encoded}),responseType:"json"});setProgress(100);setDone(true);toast({title:"File uploaded"});}catch(e:any){toast({variant:"destructive",title:"Upload failed",description:e?.message||"Please try again."});setProgress(0);}finally{setBusy(false);}};
  if(info?.error)return <main className="min-h-screen grid place-items-center bg-background p-6"><Card className="max-w-lg rounded-2xl"><CardHeader><CardTitle>Upload link unavailable</CardTitle><CardDescription>{info.error}</CardDescription></CardHeader><CardContent><Link href="/"><Button variant="outline"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Aydens Wellness Services</Button></Link></CardContent></Card></main>;
  return <main className="min-h-screen grid place-items-center bg-[#f7f2e9] dark:bg-background p-6"><Card className="w-full max-w-2xl rounded-2xl"><CardHeader><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><ShieldCheck className="h-5 w-5"/></div><CardTitle className="mt-4 text-3xl font-serif">Secure file upload</CardTitle><CardDescription>{info ? "Upload requested for "+info.clientName+". "+info.label : "Loading upload request…"}</CardDescription></CardHeader><CardContent className="space-y-5">{done?<div className="rounded-2xl border border-primary/20 bg-primary/5 p-7 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-primary"/><p className="mt-3 font-semibold">Uploaded successfully</p><p className="mt-1 text-sm text-muted-foreground">Aydens Wellness Services has received your file.</p></div>:<><button type="button" onClick={()=>inputRef.current?.click()} className="w-full rounded-2xl border-2 border-dashed border-border p-12 text-center hover:bg-muted/40"><Upload className="mx-auto h-8 w-8 text-primary"/><p className="mt-3 font-medium">{file?file.name:"Choose a file"}</p><p className="mt-1 text-xs text-muted-foreground">PDF, Word, Excel, CSV, TXT, or common images up to 10 MB.</p></button><input ref={inputRef} className="hidden" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.rtf,.png,.jpg,.jpeg,.webp,.heic,.heif" onChange={e=>setFile(e.target.files?.[0]||null)}/>{busy&&<Progress value={progress}/>}<Button className="w-full" disabled={!file||busy} onClick={()=>void submit()}>{busy?"Uploading…":"Upload file"}</Button></>}</CardContent></Card></main>;
}