import { useEffect, useRef, useState } from "react";
import { useRoute, useLocation } from "wouter";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2, FileUp, Loader2, ShieldCheck } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function UploadPage(){const [,params]=useRoute("/upload/:token");const [,setLocation]=useLocation();const {toast}=useToast();const token=params?.token||"";const ref=useRef<HTMLInputElement>(null);const [info,setInfo]=useState<any>(null);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);
 useEffect(()=>{if(token)customFetch<any>("/api/advanced/uploads/public/"+encodeURIComponent(token)).then(setInfo).catch(()=>setInfo(null))},[token]);
 const upload=async()=>{if(!file)return;setBusy(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});await customFetch("/api/advanced/uploads/public/"+encodeURIComponent(token),{method:"POST",body:JSON.stringify({fileName:file.name,mimeType:file.type,data})});setDone(true);toast({title:"Upload received"})}catch(e:any){toast({variant:"destructive",title:"Upload failed",description:e?.message||"Please try again."})}finally{setBusy(false)}};
 if(!info)return <main className="flex min-h-screen items-center justify-center bg-[#f7f2e9] p-5"><Card className="w-full max-w-xl rounded-2xl"><CardContent className="py-14 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-primary"/><CardTitle className="mt-4">This upload link is unavailable.</CardTitle><Button className="mt-5" onClick={()=>setLocation("/")}>Back to AWS</Button></CardContent></Card></main>;
 return <main className="flex min-h-screen items-center justify-center bg-[#f7f2e9] p-5 dark:bg-background"><Card className="w-full max-w-xl rounded-2xl shadow-xl"><CardHeader><p className="font-mono text-[10px] uppercase tracking-[.2em] text-destructive">Secure upload</p><CardTitle className="font-serif text-4xl">Send your file to AWS.</CardTitle><CardDescription>{info.label} · Intended for {info.clientName}. Expires {new Date(info.expiresAt).toLocaleDateString()}.</CardDescription></CardHeader><CardContent>{done?<div className="py-10 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-primary"/><h2 className="mt-4 font-serif text-3xl">We received it.</h2><Button className="mt-5" onClick={()=>setLocation("/")}>Done</Button></div>:<div className="space-y-4"><input ref={ref} hidden type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="flex w-full flex-col items-center rounded-2xl border border-dashed bg-primary/5 p-12" onClick={()=>ref.current?.click()} type="button"><FileUp className="h-8 w-8 text-primary"/><b className="mt-3">{file?.name||"Choose a document or image"}</b><span className="mt-1 text-xs text-muted-foreground">PDF, Word, Excel, CSV, TXT, or common images · max 10 MB</span></button><Button className="w-full" disabled={!file||busy} onClick={upload}>{busy?<><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Uploading…</>:<>Submit file <FileUp className="ml-2 h-4 w-4"/></>}</Button><p className="text-center text-xs text-muted-foreground">Do not upload anything you were not asked to provide.</p></div>}</CardContent></Card></main>}