import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { useClientMe, useClientBookings } from "@workspace/api-client-react";
import { customFetch } from "@workspace/api-client-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { ArrowLeft, Bot, CalendarDays, Check, FileUp, HeartHandshake, MessageCircle, NotebookPen, Plus, Send, Sparkles, Target, UserRound } from "lucide-react";

type Assignment={id:number;type:string;title:string;content:string;dueDate?:string|null;status:string;config:any;progress:any;percent:number};
type Thread={id:number;subject:string;status:string;messages:{id:number;senderType:string;senderName:string;body:string}[]};

const getJson=async<T,>(url:string,options?:RequestInit)=>customFetch<T>(url,{...options,responseType:"json"});

function AssignmentCard({item,onSave}:{item:Assignment;onSave:(progress:any)=>Promise<void>}){
 const [progress,setProgress]=useState<any>(item.progress||{});
 useEffect(()=>setProgress(item.progress||{}),[item.progress]);
 const cfg=item.config||{}; const items=Array.isArray(cfg.items)?cfg.items:[];
 const save=(next:any)=>{setProgress(next);return onSave(next)};
 return <Card className="rounded-2xl"><CardHeader><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><CardTitle>{item.title}</CardTitle><Badge variant="secondary">{item.type}</Badge></div><CardDescription className="mt-2">{item.content}</CardDescription></div><div className="text-right"><div className="font-serif text-2xl">{item.percent}%</div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">complete</div></div></div><Progress className="mt-3" value={item.percent}/></CardHeader>
 <CardContent className="space-y-4">{item.dueDate&&<p className="text-xs text-muted-foreground">Due {new Date(item.dueDate).toLocaleDateString()}</p>}
 {cfg.kind==="checklist"&&<div className="space-y-2">{items.map((label:string,index:number)=><label key={index} className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" className="mt-1 h-4 w-4" checked={progress.items?.[String(index)]===true} onChange={e=>save({...progress,items:{...(progress.items||{}),[String(index)]:e.target.checked}})}/><span>{label}</span></label>)}</div>}
 {cfg.kind==="reflection"&&<div className="space-y-2"><Label>{cfg.prompt}</Label><Textarea rows={7} value={progress.text||""} onChange={e=>setProgress({...progress,text:e.target.value})} onBlur={()=>save(progress)} placeholder="Write your reflection here…"/></div>}
 {cfg.kind==="spreadsheet"&&<Spreadsheet cfg={cfg} progress={progress} onSave={save}/>} {cfg.kind==="weekly"&&<Weekly cfg={cfg} progress={progress} onSave={save}/>}</CardContent></Card>
}

function Spreadsheet({cfg,progress,onSave}:{cfg:any;progress:any;onSave:(p:any)=>Promise<void>}){
 const columns=Array.isArray(cfg.columns)?cfg.columns:[]; const [rows,setRows]=useState<any[]>(Array.isArray(progress.rows)?progress.rows:[]);
 useEffect(()=>setRows(Array.isArray(progress.rows)?progress.rows:[]),[progress.rows]);
 const add=()=>{const row=Object.fromEntries(columns.map((c:string)=>[c,""]));const next=[...rows,row];setRows(next);return onSave({...progress,rows:next})};
 const update=(ri:number,col:string,value:string)=>setRows(rows.map((r,i)=>i===ri?{...r,[col]:value}:r));
 return <div className="space-y-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">{cfg.rowLabel||"Entries"}: {rows.length}/{cfg.requiredRows||1}</span><Button size="sm" onClick={add}><Plus className="mr-1 h-4 w-4"/>Add row</Button></div><div className="overflow-x-auto rounded-xl border"><table className="min-w-[540px] w-full"><thead><tr>{columns.map((c:string)=><th key={c} className="p-2 text-left text-xs">{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{columns.map((c:string)=><td key={c} className="p-2"><Input value={r[c]||""} onChange={e=>update(i,c,e.target.value)} onBlur={()=>onSave({...progress,rows})}/></td>)}</tr>)}</tbody></table></div></div>
}

function Weekly({cfg,progress,onSave}:{cfg:any;progress:any;onSave:(p:any)=>Promise<void>}){const done=Array.isArray(progress.completedWeeks)?progress.completedWeeks:[];const weeks=Number(cfg.weeks||1);return <div className="space-y-2">{Array.from({length:weeks}).map((_,i)=>{const checked=done.includes(i);return <label key={i} className="flex gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" className="mt-1 h-4 w-4" checked={checked} onChange={e=>onSave({...progress,completedWeeks:e.target.checked?[...new Set([...done,i])]:done.filter((w:number)=>w!==i)})}/><span><b>Week {i+1}</b><span className="mt-1 block text-muted-foreground">{cfg.weeklyPrompt||"Complete your weekly wellness activity."}</span></span></label>})}</div>}

export default function ClientTools(){
 const [,setLocation]=useLocation(); const {toast}=useToast(); const {data:session,isLoading}=useClientMe({query:{retry:false}}); const {data:bookings=[]}=useClientBookings({query:{enabled:Boolean(session?.authenticated),retry:false}});
 const [threads,setThreads]=useState<Thread[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [goals,setGoals]=useState<any[]>([]); const [journal,setJournal]=useState<any[]>([]); const [checkins,setCheckins]=useState<any[]>([]); const [files,setFiles]=useState<any[]>([]); const [assistant,setAssistant]=useState<any[]>([]);
 const [activeThread,setActiveThread]=useState<number|null>(null); const [message,setMessage]=useState(""); const [assistantText,setAssistantText]=useState(""); const [goal,setGoal]=useState(""); const [goalDescription,setGoalDescription]=useState(""); const [journalText,setJournalText]=useState(""); const [checkin,setCheckin]=useState({mood:3,stress:3,energy:3,sleep:3,notes:""}); const [aiBusy,setAiBusy]=useState(false);
 const load=async()=>{try{const data=await Promise.all([getJson<Thread[]>("/api/advanced/client/messages"),getJson<Assignment[]>("/api/advanced/client/interactive-assignments"),getJson<any[]>("/api/advanced/client/goals"),getJson<any[]>("/api/advanced/client/journal"),getJson<any[]>("/api/advanced/client/checkins"),getJson<any[]>("/api/advanced/client/uploads"),getJson<any[]>("/api/advanced/client/assistant/history")]);setThreads(data[0]||[]);setAssignments(data[1]||[]);setGoals(data[2]||[]);setJournal(data[3]||[]);setCheckins(data[4]||[]);setFiles(data[5]||[]);setAssistant(data[6]||[])}catch{}};
 useEffect(()=>{if(session?.authenticated)load()},[session?.authenticated]);
 const completion=useMemo(()=>assignments.length?Math.round(assignments.reduce((sum,a)=>sum+a.percent,0)/assignments.length):0,[assignments]); const nextBooking=bookings.find((b:any)=>b.status!=="cancelled"&&b.status!=="completed");
 if(isLoading)return <div className="flex min-h-screen items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-primary/20 border-t-primary"/></div>; if(!session?.authenticated){setLocation("/portal/login");return null;}
 const sendMessage=async()=>{if(!message.trim())return;await getJson("/api/advanced/client/messages",{method:"POST",body:JSON.stringify({threadId:activeThread||undefined,message:message.trim()})});setMessage("");await load();toast({title:"Message sent"})};
 const sendAI=async()=>{if(!assistantText.trim()||aiBusy)return;const value=assistantText.trim();setAssistant([...assistant,{role:"user",body:value}]);setAssistantText("");setAiBusy(true);try{const out=await getJson<{reply:string}>("/api/advanced/client/assistant",{method:"POST",body:JSON.stringify({message:value})});setAssistant(items=>[...items,{role:"assistant",body:out.reply}])}catch(e:any){toast({variant:"destructive",title:"Aydens Wellness Assistant is unavailable",description:e?.message||"Please try again."})}finally{setAiBusy(false)}};
 const addGoal=async()=>{if(!goal.trim())return;await getJson("/api/advanced/client/goals",{method:"POST",body:JSON.stringify({title:goal,description:goalDescription})});setGoal("");setGoalDescription("");await load()};
 const addJournal=async()=>{if(!journalText.trim())return;await getJson("/api/advanced/client/journal",{method:"POST",body:JSON.stringify({text:journalText})});setJournalText("");await load();toast({title:"Reflection saved"})};
 const addCheckin=async()=>{await getJson("/api/advanced/client/checkins",{method:"POST",body:JSON.stringify(checkin)});await load();toast({title:"Check-in saved"})};
 const saveAssignment=async(id:number,p:any)=>{await getJson("/api/advanced/client/interactive-assignments/"+id,{method:"PATCH",body:JSON.stringify({progress:p})});await load()};
 return <main className="min-h-screen bg-[#f7f2e9] text-foreground dark:bg-background"><header className="border-b bg-background/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-8"><Link href="/portal" className="inline-flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/>Client portal</Link><Button size="sm" variant="outline" onClick={()=>setLocation("/booking")}><CalendarDays className="mr-1.5 h-4 w-4"/>Book</Button></div></header>
 <div className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-8 sm:py-12"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-destructive">Your wellness space</p><h1 className="mt-2 font-serif text-5xl font-normal">My AWS</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Your appointments, wellness work, goals, reflections, messages, files, and Aydens Wellness Assistant in one place.</p></div>
 <div className="grid gap-4 sm:grid-cols-3"><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Next appointment</p><p className="mt-2 font-serif text-xl">{nextBooking?new Date(String(nextBooking.preferredDate)+"T"+String(nextBooking.preferredTime)).toLocaleDateString():"Nothing scheduled"}</p><p className="text-xs text-muted-foreground">{nextBooking?.preferredTime||"Book whenever you are ready."}</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Journey</p><p className="mt-2 font-serif text-xl">{completion}%</p><Progress className="mt-2" value={completion}/></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Files</p><p className="mt-2 font-serif text-xl">{files.length}</p><p className="text-xs text-muted-foreground">Submitted to AWS.</p></CardContent></Card></div>
 <Tabs defaultValue="assistant"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 sm:grid-cols-4 lg:grid-cols-8"><TabsTrigger value="assistant"><Bot className="mr-1 h-4 w-4"/>Assistant</TabsTrigger><TabsTrigger value="messages"><MessageCircle className="mr-1 h-4 w-4"/>Messages</TabsTrigger><TabsTrigger value="journey"><Sparkles className="mr-1 h-4 w-4"/>Journey</TabsTrigger><TabsTrigger value="goals"><Target className="mr-1 h-4 w-4"/>Goals</TabsTrigger><TabsTrigger value="journal"><NotebookPen className="mr-1 h-4 w-4"/>Journal</TabsTrigger><TabsTrigger value="checkin"><HeartHandshake className="mr-1 h-4 w-4"/>Check-in</TabsTrigger><TabsTrigger value="files"><FileUp className="mr-1 h-4 w-4"/>Files</TabsTrigger><TabsTrigger value="profile"><UserRound className="mr-1 h-4 w-4"/>Profile</TabsTrigger></TabsList>
 <TabsContent value="assistant"><Card className="rounded-2xl"><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5"/>Aydens Wellness Assistant</CardTitle><CardDescription>Supportive general wellness guidance, reflection prompts, and planning. Not a therapist or emergency service.</CardDescription></CardHeader><CardContent><div className="min-h-72 space-y-3 rounded-2xl bg-muted/20 p-4">{assistant.map((m,i)=><div key={i} className={m.role==="user"?"ml-auto max-w-[85%] rounded-2xl bg-primary p-3 text-sm text-primary-foreground":"max-w-[85%] rounded-2xl border bg-background p-3 text-sm"}>{m.body}</div>)}{!assistant.length&&<div className="flex min-h-60 items-center justify-center text-center text-sm text-muted-foreground"><div><Sparkles className="mx-auto mb-2 h-7 w-7"/>Ask the assistant to help you plan a calmer routine, reflection, or wellness habit.</div></div>}</div><div className="mt-3 flex gap-2"><Input value={assistantText} onChange={e=>setAssistantText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();sendAI()}}} placeholder="Ask the Aydens Wellness Assistant…"/><Button onClick={sendAI} disabled={aiBusy}><Send className="h-4 w-4"/></Button></div></CardContent></Card></TabsContent>
 <TabsContent value="messages"><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Conversations</CardTitle></CardHeader><CardContent className="space-y-2">{threads.map(t=><button key={t.id} onClick={()=>setActiveThread(t.id)} className="w-full rounded-xl border p-3 text-left text-sm"><b>{t.subject}</b><span className="mt-1 block text-xs text-muted-foreground">{t.status}</span></button>)}{!threads.length&&<p className="text-sm text-muted-foreground">No conversations yet.</p>}</CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle>Message AWS</CardTitle></CardHeader><CardContent><div className="min-h-52 space-y-2 rounded-xl bg-muted/20 p-3">{threads.find(t=>t.id===activeThread)?.messages.map(m=><div key={m.id} className="rounded-xl border bg-background p-3 text-sm"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{m.senderName}</p><p className="mt-1">{m.body}</p></div>)}</div><div className="mt-3 flex gap-2"><Textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message…"/><Button className="self-end" onClick={sendMessage}><Send className="mr-1 h-4 w-4"/>Send</Button></div></CardContent></Card></div></TabsContent>
 <TabsContent value="journey" className="space-y-4">{assignments.map(a=><AssignmentCard key={a.id} item={a} onSave={p=>saveAssignment(a.id,p)}/>)}{!assignments.length&&<Card className="rounded-2xl"><CardContent className="py-14 text-center text-sm text-muted-foreground">Your care team has not sent an interactive assignment yet.</CardContent></Card>}</TabsContent>
 <TabsContent value="goals"><Card className="rounded-2xl"><CardHeader><CardTitle>My goals</CardTitle><CardDescription>Set goals and keep an eye on your own progress.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2"><Input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Goal"/><Input value={goalDescription} onChange={e=>setGoalDescription(e.target.value)} placeholder="Optional description"/><Button onClick={addGoal}><Plus className="mr-1 h-4 w-4"/>Add goal</Button></div><div className="mt-5 space-y-3">{goals.map(g=><div key={g.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b>{g.title}</b><Badge variant="outline">{g.progress}%</Badge></div><Progress className="mt-2" value={g.progress}/><input className="mt-2 w-full" type="range" min="0" max="100" value={g.progress} onChange={async e=>{const p=Number(e.target.value);await getJson("/api/advanced/client/goals/"+g.id,{method:"PATCH",body:JSON.stringify({progress:p})});load()}}/></div>)}</div></CardContent></Card></TabsContent>
 <TabsContent value="journal"><Card className="rounded-2xl"><CardHeader><CardTitle>Journal & reflections</CardTitle></CardHeader><CardContent><Textarea rows={7} value={journalText} onChange={e=>setJournalText(e.target.value)} placeholder="Write whatever you want to remember…"/><Button className="mt-3" onClick={addJournal}><NotebookPen className="mr-1 h-4 w-4"/>Save reflection</Button><div className="mt-5 space-y-3">{journal.map(j=><div key={j.id} className="rounded-xl border p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{new Date(j.createdAt).toLocaleDateString()}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{j.body}</p></div>)}</div></CardContent></Card></TabsContent>
 <TabsContent value="checkin"><Card className="rounded-2xl"><CardHeader><CardTitle>Wellness check-in</CardTitle><CardDescription>Self-reported reflections, not diagnoses.</CardDescription></CardHeader><CardContent className="space-y-4">{(["mood","stress","energy","sleep"] as const).map(key=><div key={key}><div className="flex justify-between"><Label className="capitalize">{key}</Label><Badge variant="outline">{checkin[key]}/5</Badge></div><input className="w-full" type="range" min="1" max="5" value={checkin[key]} onChange={e=>setCheckin({...checkin,[key]:Number(e.target.value)})}/></div>)}<Textarea rows={3} value={checkin.notes} onChange={e=>setCheckin({...checkin,notes:e.target.value})} placeholder="Anything else?"/><Button onClick={addCheckin}><Check className="mr-1 h-4 w-4"/>Save check-in</Button></CardContent></Card></TabsContent>
 <TabsContent value="files"><Card className="rounded-2xl"><CardHeader><CardTitle>Your submitted files</CardTitle><CardDescription>Files you submit through a secure AWS upload link appear here.</CardDescription></CardHeader><CardContent className="space-y-2">{files.map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{f.fileName}</span><span className="text-xs text-muted-foreground">{Math.ceil(f.sizeBytes/1024)} KB</span></div>)}{!files.length&&<p className="text-sm text-muted-foreground">No files submitted yet.</p>}</CardContent></Card></TabsContent>
 <TabsContent value="profile"><div className="grid gap-4 sm:grid-cols-2"><Card className="rounded-2xl"><CardHeader><CardTitle>Appointments</CardTitle><CardDescription>Open the main portal to view, reschedule, or cancel appointments.</CardDescription></CardHeader><CardContent><Link href="/portal"><Button variant="outline">Open appointments</Button></Link></CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle>Need help?</CardTitle><CardDescription>Message the AWS team from the Messages tab or through the main portal.</CardDescription></CardHeader><CardContent><MessageCircle className="h-5 w-5 text-primary"/></CardContent></Card></div></TabsContent>
 </Tabs></div></main>; }