import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { customFetch } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ThemeToggle } from "@/components/theme-toggle";
import { useToast } from "@/hooks/use-toast";
import { ArrowLeft, Brain, Check, CheckCircle2, FileText, Heart, ListChecks, MessageCircle, Plus, Target, Upload, BarChart3 } from "lucide-react";

type Assignment=any;
const moods=[["1","Very low"],["2","Low"],["3","Okay"],["4","Good"],["5","Great"]];
function ProgressBar({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{width:Math.max(0,Math.min(100,value))+"%"}}/></div>}

export default function WellnessCenter(){
 const {toast}=useToast(); const [tab,setTab]=useState("assistant"); const [loading,setLoading]=useState(true);
 const [assistant,setAssistant]=useState<any[]>([]),[assistantInput,setAssistantInput]=useState(""),[assistantBusy,setAssistantBusy]=useState(false);
 const [assignments,setAssignments]=useState<Assignment[]>([]),[goals,setGoals]=useState<any[]>([]),[goalTitle,setGoalTitle]=useState(""),[goalDescription,setGoalDescription]=useState("");
 const [journal,setJournal]=useState<any[]>([]),[journalText,setJournalText]=useState(""),[checkins,setCheckins]=useState<any[]>([]);
 const [checkin,setCheckin]=useState({mood:"",stress:"",energy:"",sleep:"",notes:""}),[threads,setThreads]=useState<any[]>([]),[message,setMessage]=useState(""),[newSubject,setNewSubject]=useState("Message to Aydens Wellness Services"),[uploads,setUploads]=useState<any[]>([]),[progress,setProgress]=useState<any>(null);
 const refresh=async()=>{try{const [history,a,g,j,c,m,u,p]=await Promise.all([
   customFetch<any[]>("/api/advanced/client/assistant/history",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/interactive-assignments",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/goals",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/journal",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/checkins",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/messages",{responseType:"json"}),
   customFetch<any[]>("/api/advanced/client/uploads",{responseType:"json"}),
   customFetch<any>("/api/advanced/client/progress-summary",{responseType:"json"})
 ]);setAssistant(history);setAssignments(a);setGoals(g);setJournal(j);setCheckins(c);setThreads(m);setUploads(u);setProgress(p);}catch(e:any){toast({variant:"destructive",title:"Wellness Center could not load",description:e?.message||"Please sign in again."});}finally{setLoading(false);}};
 useEffect(()=>{void refresh();},[]);
 const sendAssistant=async(e?:React.FormEvent)=>{e?.preventDefault();if(!assistantInput.trim()||assistantBusy)return;setAssistantBusy(true);const value=assistantInput.trim();setAssistantInput("");setAssistant(items=>[...items,{role:"user",body:value,createdAt:new Date().toISOString()}]);try{const result=await customFetch<any>("/api/advanced/client/assistant",{method:"POST",body:JSON.stringify({message:value}),responseType:"json"});setAssistant(items=>[...items,{role:"assistant",body:result.reply,createdAt:new Date().toISOString()}]);}catch(error:any){toast({variant:"destructive",title:"Aydens Wellness Assistant is unavailable",description:error?.message||"Please try again."});}finally{setAssistantBusy(false);}};
 const saveAssignment=async(id:number,p:any)=>{try{await customFetch("/api/advanced/client/interactive-assignments/"+id,{method:"PATCH",body:JSON.stringify({progress:p}),responseType:"json"});await refresh();}catch(error:any){toast({variant:"destructive",title:"Could not save progress",description:error?.message||"Try again."});}};
 const addGoal=async(e:React.FormEvent)=>{e.preventDefault();if(!goalTitle.trim())return;try{await customFetch("/api/advanced/client/goals",{method:"POST",body:JSON.stringify({title:goalTitle,description:goalDescription}),responseType:"json"});setGoalTitle("");setGoalDescription("");await refresh();toast({title:"Goal added"});}catch(error:any){toast({variant:"destructive",title:"Could not add goal",description:error?.message||"Try again."});}};
 const saveJournal=async(e:React.FormEvent)=>{e.preventDefault();if(!journalText.trim())return;try{await customFetch("/api/advanced/client/journal",{method:"POST",body:JSON.stringify({text:journalText}),responseType:"json"});setJournalText("");await refresh();toast({title:"Journal entry saved"});}catch(error:any){toast({variant:"destructive",title:"Could not save journal entry",description:error?.message||"Try again."});}};
 const saveCheckin=async(e:React.FormEvent)=>{e.preventDefault();try{const payload:any={notes:checkin.notes};["mood","stress","energy","sleep"].forEach(k=>{if(checkin[k as keyof typeof checkin])payload[k]=Number(checkin[k as keyof typeof checkin]);});await customFetch("/api/advanced/client/checkins",{method:"POST",body:JSON.stringify(payload),responseType:"json"});setCheckin({mood:"",stress:"",energy:"",sleep:"",notes:""});await refresh();toast({title:"Check-in saved"});}catch(error:any){toast({variant:"destructive",title:"Could not save check-in",description:error?.message||"Use ratings from 1–5."});}};
 const sendMessage=async(e:React.FormEvent)=>{e.preventDefault();if(!message.trim())return;try{await customFetch("/api/advanced/client/messages",{method:"POST",body:JSON.stringify({threadId:threads[0]?.id,subject:newSubject,message}),responseType:"json"});setMessage("");await refresh();toast({title:"Message sent"});}catch(error:any){toast({variant:"destructive",title:"Message failed",description:error?.message||"Try again."});}};
 const assignmentCard=(a:Assignment)=>{const cfg=a.config||{},value=a.progress&&typeof a.progress==="object"?a.progress:{};
   if(cfg.kind==="checklist"){const items=Array.isArray(cfg.items)?cfg.items:[];return <div className="mt-4 space-y-3">{items.map((item:string,i:number)=><label key={i} className="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" checked={value.items?.[String(i)]===true} onChange={e=>void saveAssignment(a.id,{...value,items:{...(value.items||{}),[String(i)]:e.target.checked}})} className="mt-1 h-4 w-4"/><span className="text-sm">{item}</span></label>)}</div>;}
   if(cfg.kind==="reflection")return <div className="mt-4"><Textarea defaultValue={value.text||""} onBlur={e=>void saveAssignment(a.id,{...value,text:e.target.value})} placeholder={cfg.prompt||"Write your reflection…"} rows={7}/></div>;
   if(cfg.kind==="weekly"){const weeks=Math.max(1,Number(cfg.weeks||1)),done=new Set(Array.isArray(value.completedWeeks)?value.completedWeeks:[]);return <div className="mt-4 grid gap-2 sm:grid-cols-2">{Array.from({length:weeks},(_,i)=>i+1).map(w=><button type="button" key={w} onClick={()=>{const n=new Set(done);n.has(w)?n.delete(w):n.add(w);void saveAssignment(a.id,{...value,completedWeeks:[...n]});}} className={"rounded-xl border p-4 text-left "+(done.has(w)?"border-primary/30 bg-primary/10":"hover:bg-muted")}><div className="flex justify-between"><span className="font-medium">Week {w}</span>{done.has(w)?<CheckCircle2 className="h-5 w-5 text-primary"/>:<ListChecks className="h-5 w-5 text-muted-foreground"/>}</div><p className="mt-2 text-xs text-muted-foreground">{cfg.weeklyPrompt||"Complete this week's activity."}</p></button>)}</div>;}
   if(cfg.kind==="spreadsheet"){const cols=Array.isArray(cfg.columns)?cfg.columns:[],list=Array.isArray(value.rows)?value.rows:[];const add=()=>void saveAssignment(a.id,{...value,rows:[...list,Object.fromEntries(cols.map((c:string)=>[c,""]))]});return <div className="mt-4 space-y-3"><div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-sm"><thead><tr>{cols.map((c:string)=><th key={c} className="p-3 text-left">{c}</th>)}</tr></thead><tbody>{list.map((row:any,ri:number)=><tr key={ri} className="border-t">{cols.map((c:string)=><td key={c} className="p-2"><Input value={row[c]||""} onChange={e=>setAssignments(items=>items.map(x=>x.id===a.id?{...x,progress:{...value,rows:list.map((r:any,i:number)=>i===ri?{...r,[c]:e.target.value}:r)}}:x))} onBlur={()=>{const current=assignments.find(x=>x.id===a.id);if(current)void saveAssignment(a.id,current.progress);}}/></td>)}</tr>)}</tbody></table></div><Button type="button" variant="outline" onClick={add}><Plus className="mr-2 h-4 w-4"/>Add row</Button><p className="text-xs text-muted-foreground">Target: {cfg.requiredRows||1} rows.</p></div>;}
   return null;};
 const avg=progress?.checkinAverage||{}; if(loading)return <div className="min-h-screen grid place-items-center">Loading your Wellness Center…</div>;
 return <main className="min-h-screen bg-[#f7f2e9] dark:bg-background"><header className="border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-8"><div className="flex items-center gap-3"><Link href="/portal" className="rounded-full border p-2"><ArrowLeft className="h-4 w-4"/></Link><div><p className="font-mono text-[9px] font-bold uppercase tracking-[.2em] text-destructive">Private client space</p><h1 className="font-serif text-2xl">Wellness Center</h1></div></div><ThemeToggle compact/></div></header>
 <div className="mx-auto max-w-7xl px-4 py-8 sm:px-8"><div className="mb-8 grid gap-4 md:grid-cols-4">{[
  ["Assignment progress",(progress?.assignmentAverage||0)+"%",<Heart className="h-4 w-4"/>],
  ["Goal progress",(progress?.goalAverage||0)+"%",<Target className="h-4 w-4"/>],
  ["Journal entries",String(progress?.journalCount||0),<FileText className="h-4 w-4"/>],
  ["Sessions completed",String(progress?.sessionCount||0),<CheckCircle2 className="h-4 w-4"/>]
 ].map(([label,value,icon])=><Card key={String(label)} className="rounded-2xl"><CardContent className="p-5"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><p className="mt-2 text-3xl font-semibold">{value}</p>{String(label).includes("progress")&&<ProgressBar value={Number(String(value).replace("%",""))}/>}</CardContent></Card>)}</div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto flex flex-wrap"><TabsTrigger value="assistant"><Brain className="mr-1.5 h-4 w-4"/>Assistant</TabsTrigger><TabsTrigger value="messages"><MessageCircle className="mr-1.5 h-4 w-4"/>Messages</TabsTrigger><TabsTrigger value="assignments"><Heart className="mr-1.5 h-4 w-4"/>Journey</TabsTrigger><TabsTrigger value="goals"><Target className="mr-1.5 h-4 w-4"/>Goals</TabsTrigger><TabsTrigger value="journal"><FileText className="mr-1.5 h-4 w-4"/>Journal</TabsTrigger><TabsTrigger value="checkins"><BarChart3 className="mr-1.5 h-4 w-4"/>Check-ins</TabsTrigger><TabsTrigger value="uploads"><Upload className="mr-1.5 h-4 w-4"/>Uploads</TabsTrigger></TabsList>
 <TabsContent value="assistant" className="mt-6"><Card className="rounded-2xl overflow-hidden"><CardHeader className="bg-primary/5"><CardTitle className="flex items-center gap-2"><Brain className="h-5 w-5 text-primary"/>Aydens Wellness Assistant</CardTitle><CardDescription>Aubrey can help with general wellness ideas, reflection prompts, organization and encouragement. Aubrey is not a therapist or emergency service.</CardDescription></CardHeader><CardContent><div className="h-[55vh] overflow-y-auto space-y-3 p-2">{assistant.length===0?<div className="rounded-xl bg-muted/30 p-6 text-sm text-muted-foreground">Hi! I’m the Aydens Wellness Assistant. What would you like help thinking through today?</div>:assistant.map((m:any,i:number)=><div key={i} className={"rounded-2xl p-4 "+(m.role==="assistant"?"bg-primary/10 mr-8":"bg-muted ml-8")}><p className="whitespace-pre-wrap text-sm leading-6">{m.body}</p></div>)}</div><form onSubmit={sendAssistant} className="mt-4 flex gap-2"><Input value={assistantInput} onChange={e=>setAssistantInput(e.target.value)} placeholder="Ask Aubrey something…"/><Button disabled={assistantBusy}>{assistantBusy?"Thinking…":"Send"}</Button></form></CardContent></Card></TabsContent>
 <TabsContent value="messages" className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Message the team</CardTitle><CardDescription>Private coordination and support messages.</CardDescription></CardHeader><CardContent><form onSubmit={sendMessage} className="space-y-4"><Input value={newSubject} onChange={e=>setNewSubject(e.target.value)}/><Textarea value={message} onChange={e=>setMessage(e.target.value)} rows={7} placeholder="Write your message…"/><Button disabled={!message.trim()}>Send message</Button></form></CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle>Your conversations</CardTitle></CardHeader><CardContent className="space-y-4">{threads.map((t:any)=><div key={t.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{t.subject}</p><Badge variant="secondary">{t.status}</Badge></div><div className="mt-3 space-y-2">{t.messages.map((m:any)=><div key={m.id} className={"rounded-xl p-3 text-sm "+(m.senderType==="staff"?"bg-primary/10":"bg-muted")}><p className="mb-1 text-xs text-muted-foreground">{m.senderName}</p>{m.body}</div>)}</div></div>)}{!threads.length&&<p className="text-sm text-muted-foreground">No conversations yet.</p>}</CardContent></Card></TabsContent>
 <TabsContent value="assignments" className="mt-6 space-y-4">{assignments.map((a:any)=><Card key={a.id} className="rounded-2xl"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{a.title}</CardTitle><CardDescription>{a.content}</CardDescription></div><Badge>{a.percent||0}%</Badge></div></CardHeader><CardContent><ProgressBar value={a.percent||0}/>{assignmentCard(a)}<p className="mt-3 text-xs text-muted-foreground">{a.dueDate?("Due "+a.dueDate+" · "):""}{a.frequency==="weekly"?"Weekly":"Assignment"}{a.status==="completed"?" · Completed":""}</p></CardContent></Card>)}{!assignments.length&&<Card className="rounded-2xl"><CardContent className="p-8 text-center text-sm text-muted-foreground">No interactive assignments yet.</CardContent></Card>}</TabsContent>
 <TabsContent value="goals" className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Set a personal goal</CardTitle></CardHeader><CardContent><form onSubmit={addGoal} className="space-y-4"><Input value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="e.g. Build a calmer bedtime routine"/><Textarea value={goalDescription} onChange={e=>setGoalDescription(e.target.value)} placeholder="What would success look like?"/><Button><Plus className="mr-2 h-4 w-4"/>Add goal</Button></form></CardContent></Card><div className="space-y-4">{goals.map((g:any)=><Card key={g.id} className="rounded-2xl"><CardHeader><CardTitle>{g.title}</CardTitle><CardDescription>{g.description}</CardDescription></CardHeader><CardContent><div className="flex justify-between text-xs text-muted-foreground"><span>{g.status}</span><span>{g.progress}%</span></div><ProgressBar value={g.progress}/><input className="mt-4 w-full" type="range" min="0" max="100" value={g.progress} onChange={async e=>{const p=Number(e.target.value);setGoals(items=>items.map(item=>item.id===g.id?{...item,progress:p}:item));try{await customFetch("/api/advanced/client/goals/"+g.id,{method:"PATCH",body:JSON.stringify({progress:p}),responseType:"json"});}catch{}}}/></CardContent></Card>)}</div></TabsContent>
 <TabsContent value="journal" className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>Private journal</CardTitle><CardDescription>Write reflections that belong to you.</CardDescription></CardHeader><CardContent><form onSubmit={saveJournal} className="space-y-4"><Textarea rows={9} value={journalText} onChange={e=>setJournalText(e.target.value)} placeholder="What’s on your mind today?"/><Button>Save entry</Button></form></CardContent></Card><div className="space-y-4">{journal.map((j:any)=><Card key={j.id} className="rounded-2xl"><CardHeader><CardDescription>{new Date(j.createdAt).toLocaleString()}</CardDescription></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-6">{j.body}</p></CardContent></Card>)}</div></TabsContent>
 <TabsContent value="checkins" className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-2xl"><CardHeader><CardTitle>How are you doing?</CardTitle><CardDescription>This is a wellness check-in, not a diagnosis.</CardDescription></CardHeader><CardContent><form onSubmit={saveCheckin} className="space-y-4">{[["mood","Mood"],["stress","Stress"],["energy","Energy"],["sleep","Sleep"]].map(([key,label])=><div key={key}><label className="text-sm font-medium">{label}</label><div className="mt-2 flex flex-wrap gap-2">{moods.map(([v,l])=><button key={v} type="button" onClick={()=>setCheckin({...checkin,[key]:v})} className={"rounded-full border px-3 py-1.5 text-xs "+(checkin[key as keyof typeof checkin]===v?"border-primary bg-primary/10":"")}>{v} · {l}</button>)}</div></div>)}<Textarea value={checkin.notes} onChange={e=>setCheckin({...checkin,notes:e.target.value})} placeholder="Anything you want to remember?"/><Button><Check className="mr-2 h-4 w-4"/>Save check-in</Button></form></CardContent></Card><Card className="rounded-2xl"><CardHeader><CardTitle>Recent check-ins</CardTitle><CardDescription>Recent averages: mood {avg.mood||"—"}, stress {avg.stress||"—"}, energy {avg.energy||"—"}, sleep {avg.sleep||"—"}.</CardDescription></CardHeader><CardContent className="space-y-3">{checkins.map((c:any)=><div key={c.id} className="rounded-xl border p-3 text-sm"><div className="flex gap-3 text-xs"><span>Mood {c.mood??"—"}</span><span>Stress {c.stress??"—"}</span><span>Energy {c.energy??"—"}</span><span>Sleep {c.sleep??"—"}</span></div>{c.notes&&<p className="mt-2 text-muted-foreground">{c.notes}</p>}</div>)}</CardContent></Card></TabsContent>
 <TabsContent value="uploads" className="mt-6"><Card className="rounded-2xl"><CardHeader><CardTitle>Your uploaded files</CardTitle><CardDescription>Files you submitted through Aydens Wellness Services upload requests.</CardDescription></CardHeader><CardContent className="space-y-3">{uploads.map((u:any)=><div key={u.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{u.fileName}</p><p className="text-xs text-muted-foreground">{u.label} · {Math.max(1,Math.round(Number(u.sizeBytes)/1024))} KB</p></div><span className="text-xs text-muted-foreground">{new Date(u.createdAt).toLocaleDateString()}</span></div>)}{!uploads.length&&<p className="text-sm text-muted-foreground">No uploaded files yet.</p>}</CardContent></Card></TabsContent>
 </Tabs></div></main>;
}